---
dependencies:
  another_flutter_splash_screen: ^1.2.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  file_picker: 8.1.4
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.0.2
  flutter_chat_core: ^0.0.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^2.0.0-dev.1
  flutter_map: ^7.0.2
  flyer_chat_image_message: ^0.0.2
  flyer_chat_text_message: ^0.0.2
  geolocator: ^13.0.2
  go_router: ^14.6.2
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  latlong2: ^0.9.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sembast: ^3.8.0+1
  shared_preferences: ^2.3.3
  stream_chat_flutter: ^8.3.0
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 
  build_runner:
environment:
  sdk: '>=3.4.1 <4.0.0'
flutter:
  assets:
    - assets/
  uses-material-design: true
name: test_project
publish_to: none
version: 1.0.0+1